package section24errorhandling

import "testing"

func TestRecoverExam1(t *testing.T) {
	recoverExam()
}